package com.example.yangiliklarwebsaytbackend.Entity.Enums;

public enum Huquqlar {
    ADDPOST,EDITPOST,DELETEPOST,READPOST,
    ADDCOMMENT,EDITCOMMENT,DELETECOMMENT,READCOMMENT,DELETEMYCOMMENT,
    ADDUSER,DELETEUSER,EDITUSER,READUSER,
    ADDLAVOZIM,EDITLAVOZIM,DELETELAVOZIM,READLAVOZIM,
    BLOCKUSER
}
